apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zitadel
resources:
  - ../../base/zitadel
  - virtualservice.yaml
  - postgres-repo.yaml
  - postgresql-release.yaml
patchesStrategicMerge:
  - values.yaml
