apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: zitadel
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql # Name of the helm chart
      sourceRef:
        kind: HelmRepository # <HelmRepository|GitRepository|Bucket>
        name: postgresql
        namespace: postgres
      interval: 1m
  values:
    auth:
      username: postgres
      password: postgres123
      database: zitadel
        host    all             all             all                    trust
    initdb:
      user: postgres
      password: postgres123
      database: zitadel
