apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  values:
    zitadel:
      masterkey: x123456789012345678901234567891y
      configmapConfig:
        ExternalSecure: false
        ExternalDomain: zitadel.admin.dev.techbrewhq.com
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: postgres-postgresql.postgres.svc.cluster.local
            Port: 5432
            Database: zitadel
            MaxOpenConns: 20
            MaxIdleConns: 10
            MaxConnLifetime: 30m
            MaxConnIdleTime: 5m
            User:
              Username: postgres
              SSL:
                Mode: disable
            Admin:
              Username: postgres
              SSL:
                Mode: disable
