apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 1m
  values:
    crds:
      enabled: false
    grafana:
      enabled: true
      adminPassword: "admin"  # Change this in the demo overlay
      env:
        GF_SERVER_ROOT_URL: "https://grafana.admin.dev.techbrewhq.com"
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak"
        GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
        GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: "email"
        GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'grafana-admins') && 'Admin' || 'Viewer'"
      ingress:
        enabled: true
        ingressClassName: "istio"
        hosts:
          - grafana.admin.dev.techbrewhq.com
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
    prometheus:
      prometheusSpec:
        podMetadata:
          annotations:
            proxy.istio.io/config: |
              proxyMetadata:
                OUTPUT_CERTS: /etc/istio-output-certs
            sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
            traffic.sidecar.istio.io/includeOutboundIPRanges: ""
          labels:
            app: prometheus
        enableFeatures:
          - remote-write-receiver
        additionalConfig:
          scrapeClasses:
            - name: istio-certs
              default: true
              tlsConfig:
                caFile: /etc/prom-certs/root-cert.pem
                certFile: /etc/prom-certs/cert-chain.pem
                keyFile: /etc/prom-certs/key.pem
                insecureSkipVerify: true
        volumeMounts:
          - mountPath: /etc/prom-certs/
            name: istio-certs
        volumes:
          - name: istio-certs
            emptyDir:
              medium: Memory
    prometheusOperator:
      admissionWebhooks:
        patch:
          podAnnotations:
            sidecar.istio.io/inject: "false"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
    alertmanager:
      alertmanagerSpec:
        podMetadata:
          annotations:
            proxy.istio.io/config: |
              proxyMetadata:
                OUTPUT_CERTS: /etc/istio-output-certs
            sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
            traffic.sidecar.istio.io/includeOutboundIPRanges: ""
        scheme: "https"
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
          insecureSkipVerify: true
        volumeMounts:
          - mountPath: /etc/prom-certs/
            name: istio-certs
        volumes:
          - name: istio-certs
            emptyDir:
              medium: Memory
 