---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-admin-gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: istio-admin-gateway
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.admin.dev.techbrewhq.com"
  dnsNames:
    - "*.admin.dev.techbrewhq.com"
  privateKey:
    rotationPolicy: Always
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-admin-gateway
  namespace: istio-admin-gateway
spec:
  releaseName: istio-admin-gateway
  interval: 10m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.24.2" # Adjust based on your Istio version
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 172.18.0.101 # Ensure this falls within MetalLB's IP range
      ports:
        - name: https
          port: 443
          targetPort: 8443

    deployment:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5

    image:
      repository: docker.io/istio/proxyv2
      tag: "1.24.2"
      pullPolicy: IfNotPresent

    gateways:
      enabled: true
      name: istio-admin-gateway
      selector:
        istio: istio-admin-gateway # Ensure this matches the pod labels
      servers:
        - hosts:
            - "*.admin.dev.techbrewhq.com"
          port:
            name: http-admin
            number: 80
            protocol: HTTP
          tls:
            httpsRedirect: true
        - hosts:
            - "*.admin.dev.techbrewhq.com"
          port:
            name: https-admin
            number: 443
            protocol: HTTPS
          tls:
            credentialName: gateway-tls
            minProtocolVersion: TLSV1_3
            mode: SIMPLE
        - hosts:
            - keycloak.admin.dev.techbrewhq.com
          port:
            name: http-keycloak
            number: 80
            protocol: HTTP
          tls:
            httpsRedirect: true
        - hosts:
            - keycloak.admin.dev.techbrewhq.com
          port:
            name: https-keycloak
            number: 443
            protocol: HTTPS
          tls:
            credentialName: gateway-tls
            minProtocolVersion: TLSV1_3
            mode: OPTIONAL_MUTUAL
