---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-tenant-gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: istio-tenant-gateway
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.dev.techbrewhq.com"
  dnsNames:
    - "*.dev.techbrewhq.com"
  privateKey:
    rotationPolicy: Always

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-tenant-gateway
  namespace: istio-tenant-gateway
spec:
  releaseName: istio-tenant-gateway
  interval: 10m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.24.2" # Adjust based on your Istio version
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 172.18.0.102 # Ensure this falls within MetalLB's IP range
      ports:
        - name: http
          port: 80
          targetPort: 80
        - name: https
          port: 443
          targetPort: 43

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: {}
      autoscaleBehavior: {}

    image:
      repository: docker.io/istio/proxyv2
      tag: "1.24.2"
      pullPolicy: IfNotPresent
