---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-tenant-gateway
  labels:
    istio-injection: enabled
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
  namespace: istio-tenant-gateway
spec:
  secretName: gateway-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.dev.techbrewhq.com"
  dnsNames:
    - "*.dev.techbrewhq.com"
  privateKey:
    rotationPolicy: Always

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-tenant-gateway
  namespace: istio-tenant-gateway
spec:
  releaseName: istio-tenant-gateway
  interval: 10m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: "1.24.2" # Adjust based on your Istio version
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 172.18.0.102 # Ensure this falls within MetalLB's IP range
      ports:
        - name: http
          port: 80
          targetPort: 8080
        - name: https
          port: 443
          targetPort: 8443

    deployment:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5

    image:
      repository: docker.io/istio/proxyv2
      tag: "1.24.2"
      pullPolicy: IfNotPresent

    gateways:
      enabled: true
      name: istio-tenant-gateway
      selector:
        istio: tenant-gateway # Ensure this matches the pod labels
      servers:
        - port:
            number: 443
            name: https
            protocol: HTTPS
        - port:
            number: 80
            name: http
            protocol: HTTP
          hosts:
            - "*.dev.techbrewhq.com"
          tls:
            mode: SIMPLE
            credentialName: gateway-tls # Must match the cert-manager secret name
