apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-tenant-gateway
  namespace: istio-tenant-gateway
spec:
  selector:
    istio: tenant-gateway # Must match the gateway pod labels
  servers:
    - hosts:
        - sso.dev.techbrewhq.com
      port:
        name: http-keycloak
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - sso.dev.techbrewhq.com
      port:
        name: https-keycloak
        number: 443
        protocol: HTTPS
      tls:
        credentialName: gateway-tls
        minProtocolVersion: TLSV1_3
        mode: OPTIONAL_MUTUAL
    - hosts:
        - "*.dev.techbrewhq.com"
      port:
        name: http-tenant
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - "*.dev.techbrewhq.com"
      port:
        name: https-tenant
        number: 443
        protocol: HTTPS
      tls:
        credentialName: gateway-tls
        minProtocolVersion: TLSV1_3
        mode: SIMPLE
