apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 1m
  values:
    auth:
      adminUser: admin
      adminPassword: "admin123!"
    extraEnvVars:
      - name: KC_HOSTNAME
        value: "keycloak.admin.dev.techbrewhq.com"
      - name: KC_PROXY
        value: "passthrough"
        value: "true"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "false"
      - name: KC_HTTPS_ENABLED
        value: "true"
      - name: KC_HTTPS_PORT
        value: "8443"
      - name: KEYCLOAK_EXTRA_ARGS
        value: "--import-realm"
      - name: KC_FRONTEND_URL
        value: "https://keycloak.admin.dev.techbrewhq.com"
      - name: realm-config
        configMap:
          name: keycloak-realm
    extraVolumeMounts:
      - name: realm-config
        mountPath: /opt/bitnami/keycloak/data/import/
    service:
      type: ClusterIP
      ports:
        http: 8080
        https: 8443
    replicaCount: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
