apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak # Name of the helm chart
      version: "24.4.0"
      sourceRef:
        kind: HelmRepository # <HelmRepository|GitRepository|Bucket>
        name: keycloak
        namespace: keycloak
      interval: 1m
  values:
    auth:
      adminUser: admin
      adminPassword: "admin123!"
    extraEnvVars:
      - name: KC_HOSTNAME
        value: "https://keycloak.admin.dev.techbrewhq.com"
      - name: KC_PROXY
        value: "edge"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_RELATIVE_PATH
        value: "/"
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_PRODUCTION
        value: "true"
    replicaCount: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    extraConfigMapData:
      realm.json: |
        {
          "realm": "techbrew",
          "enabled": true,
          "displayName": "TechBrew",
          "loginTheme": "keycloak",
          "accessTokenLifespan": 300,
          "ssoSessionIdleTimeout": 1800,
          "ssoSessionMaxLifespan": 36000,
          "defaultGroups": ["users"],
          "groups": [
            {
              "name": "grafana-admins",
              "path": "/grafana-admins"
            }
          ],
          "roles": {
            "realm": [
              {
                "name": "grafana-admin",
                "description": "Grafana administrator role"
              }
            ]
          },
          "clients": [
            {
              "clientId": "grafana",
              "enabled": true,
              "clientAuthenticatorType": "client-secret",
              "secret": "grafana-client-secret-12345",
              "redirectUris": [
                "https://grafana.admin.dev.techbrewhq.com/*"
              ],
              "webOrigins": [
                "https://grafana.admin.dev.techbrewhq.com"
              ],
              "protocol": "openid-connect",
              "publicClient": false,
              "standardFlowEnabled": true,
              "implicitFlowEnabled": false,
              "directAccessGrantsEnabled": true,
              "serviceAccountsEnabled": true,
              "defaultClientScopes": [
                "email",
                "profile"
              ],
              "protocolMappers": [
                {
                  "name": "groups",
                  "protocol": "openid-connect",
                  "protocolMapper": "oidc-group-membership-mapper",
                  "config": {
                    "claim.name": "groups",
                    "full.path": "true",
                    "id.token.claim": "true",
                    "access.token.claim": "true",
                    "userinfo.token.claim": "true"
                  }
                }
              ]
            }
          ]
        }
