apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak
      version: "24.4.0"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 1m
  values:
    auth:
      adminUser: admin
      adminPassword: "admin123!"
    extraEnvVars:
      - name: KC_HOSTNAME
        value: "https://keycloak.admin.dev.techbrewhq.com"
      - name: KC_PROXY
        value: "edge"
      - name: KC_HOSTNAME_STRICT
        value: "false"
      - name: KC_HOSTNAME_STRICT_HTTPS
        value: "true"
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_RELATIVE_PATH
        value: "/"
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_PRODUCTION
        value: "true"
      - name: KEYCLOAK_EXTRA_ARGS
        value: "--import-realm"
    extraVolumes:
      - name: realm-config
        configMap:
          name: keycloak-realm
    extraVolumeMounts:
      - name: realm-config
        mountPath: /opt/bitnami/keycloak/data/import/
    replicaCount: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
