apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak
      version: "24.4.0"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 1m
  values:
    auth:
      adminUser: admin
      adminPassword: "admin123!"
    extraEnvVars:
      - name: KC_HOSTNAME
        value: "https://sso.dev.techbrewhq"
      - name: KC_HOSTNAME_ADMIN
        value: "https://keycloak.admin.dev.techbrewhq.com"
      - name: KC_PROXY
        value: "edge"
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KEYCLOAK_EXTRA_ARGS
        value: "--import-realm"
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KC_PROXY_HEADERS
        value: "xforwarded"
    service:
      type: ClusterIP
      http:
        enabled: true
      ports:
        http: 8080
    replicaCount: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
