apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 1m
  chart:
    spec:
      chart: keycloak
      version: "24.4.0"
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: keycloak
      interval: 1m
  values:
    auth:
      adminUser: admin
      adminPassword: "admin123!"
    extraEnvVars:
      - name: KC_HOSTNAME
        value: "http://sso.dev.techbrewhq"
      - name: KC_HOSTNAME_ADMIN
        value: "http://keycloak.admin.dev.techbrewhq.com"
      - name: KC_HTTP_ENABLED
        value: "true"
    proxyAddressForwarding: true
    service:
      type: ClusterIP
      http:
        enabled: true
      ports:
        http: 8080
        https: 8443
    replicaCount: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    logging:
      output: json
      level: DEBUG
