apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base/keycloak
  - admin-access-vs.yaml
  - keycloak-tenant-rm-pubpath-vs.yaml
  - public-access-vs.yaml
  - realm-configmap.yaml
patchesStrategicMerge:
  - keycloak-values.yaml
