apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base/keycloak
  - virtualservice.yaml
  - realm-configmap.yaml
patchesStrategicMerge:
  - keycloak-values.yaml
