apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  gateways:
    - istio-admin-gateway/istio-admin-gateway
  hosts:
    - keycloak.admin.dev.techbrewhq.com
  http:
    - route:
        - destination:
            host: keycloak.keycloak.svc.cluster.local
            port:
              number: 8080
