apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  gateways:
    - istio-admin-gateway/istio-admin-gateway # Reference the admin gateway
  hosts:
    - keycloak.admin.dev.techbrewhq.com
  http:
    - route:
        - destination:
            host: keycloak-headless.keycloak.svc.cluster.local # Fully qualified service name
            port:
              number: 8080 # Default Keycloak port (adjust if needed)
