apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1m
  chart:
    spec:
      chart: zitadel
      version: 8.13.1
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: zitadel
      interval: 1m
  values: {}
