---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 15m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb 
  namespace: metallb-system 
spec:
  interval: 15m
  releaseName: metallb
  chart:
    spec:
      chart: metallb 
      version: '0.14.9'
      sourceRef:
        kind: HelmRepository
        name: metallb 
        namespace: flux-system
      interval: 10m
  values: {}
