---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 15m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: "0.14.9"
  interval: 15m
  values:
    speaker:
      enabled: true
      hostNetwork: false # Disable host networking
      hostPorts: [] # Disable host ports
      securityContext:
        capabilities:
          drop:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN # Remove capabilities that are restricted by PodSecurity
    controller:
      enabled: true
      hostNetwork: false # Disable host networking on controller as well
      hostPorts: [] # Disable host ports on controller
      securityContext:
        capabilities:
          drop:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN # Remove capabilities that are restricted by PodSecurity
