---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: cert-manager
type: Opaque
stringData:
  api-key: "DF2jemYLqL3-CvVAE3cnxrdnpEyHL7l0iB_mQrVG"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: joshuabrewer.d@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cert-manager
    solvers:
      - dns01:
          cloudflare:
            email: "joshuabrewer.d@gmail.com"
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
