apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool 
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.100-172.18.0.105
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement 
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool 
