apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 1m
  chart:
    spec:
      chart: postgres # Name of the helm chart
      sourceRef:
        kind: HelmRepository # <HelmRepository|GitRepository|Bucket>
        name: postgresql
        namespace: postgres
      interval: 1m
  values:
    primary:
      pgHbaConfiguration: |
        host all all all trust
