apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql # Name of the helm chart
      sourceRef:
        kind: HelmRepository # <HelmRepository|GitRepository|Bucket>
        name: postgresql
        namespace: postgres
      interval: 1m
  values:
    global:
      postgresql:
        auth:
          username: "zitadel"
          password: "xyz" # This should match the password in your Zitadel secretConfig
          database: "zitadel"
          postgresPassword: "abc" # This should match the admin password in Zitadel secretConfig
    primary:
      pgHbaConfiguration: |
        host all all all trust
