apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/monitoring
  - virtualservice.yaml
  - grafana-oauth-secret.yaml
patchesStrategicMerge:
  - values.yaml 