apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  values:
    grafana:
      adminPassword: "grafana123!" # Change this to a secure password
      envFrom:
        - secretRef:
            name: grafana-oauth
      env:
        GF_SERVER_ROOT_URL: "https://grafana.admin.dev.techbrewhq.com"
        GF_SERVER_DOMAIN: "grafana.admin.dev.techbrewhq.com"
        GF_SERVER_PROTOCOL: "https"
        GF_SERVER_CERT_FILE: "/etc/grafana/certs/tls.crt" # Make sure environment var matches path
        GF_SERVER_CERT_KEY: "/etc/grafana/certs/tls.key" # Make sure environment var matches path
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://keycloak.admin.dev.techbrewhq.com/realms/techbrew/protocol/openid-connect/auth"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://keycloak.admin.dev.techbrewhq.com/realms/techbrew/protocol/openid-connect/token"
        GF_AUTH_GENERIC_OAUTH_API_URL: "https://keycloak.admin.dev.techbrewhq.com/realms/techbrew/protocol/openid-connect/userinfo"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          valueFrom:
            secretKeyRef:
              name: grafana-oauth
              key: client-secret
      grafana.ini:
        server:
          root_url: https://grafana.admin.dev.techbrewhq.com
          domain: grafana.admin.dev.techbrewhq.com
          protocol: https
          cert_file: /etc/grafana/certs/tls.crt # Explicitly set certificate path
          cert_key: /etc/grafana/certs/tls.key # Explicitly set key path
        auth:
          disable_login_form: false
        auth.generic_oauth:
          enabled: true
          allow_sign_up: true
          scopes: "openid profile email"
          email_attribute_path: "email"
          groups_attribute_path: "groups"
          role_attribute_path: "contains(groups[*], 'grafana-admins') && 'Admin' || 'Viewer'"
          tls_skip_verify_insecure: false
      extraVolumes:
        - name: grafana-tls
          secret:
            secretName: grafana-tls
      extraVolumeMounts:
        - name: grafana-tls
          mountPath: /etc/grafana/certs/
